# Generated by Django 5.2 on 2025-04-23 12:38

import django.db.models.deletion
import package.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('allowed_groups', models.ManyToManyField(related_name='allowed_packages', to='auth.group')),
                ('contributors', models.ManyToManyField(related_name='packages_contributed', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(related_name='usages', to='package.package')),
                ('subscribers', models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('path', models.FileField(upload_to=package.models.version_path)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='package.package')),
            ],
        ),
    ]
