# Generated by Django 5.2 on 2025-04-23 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_packages', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='package',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='packages_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='usages', to='package.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
